version: '3.6'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${POSTGRES_TARGET_DB}
      DATABASE_HOST: ${POSTGRES_SERVER}
      DATABASE_PORT: ${POSTGRES_SERVER_PORT}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SSL: true
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
  caddy:
    image: caddy:2.3.0
    depends_on:
    - strapi
    restart: always
    environment:
    - "CADDY_SITE_ADDRESS=${CADDY_SITE_ADDRESS}"   
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
volumes:
  caddy_data:
  caddy_config: